export const ROUTER_PATH = {
    //ROUTER_COMMON
    HOME: "/",
    EMPTY: "",
    ADD: "add",
    EDIT: "edit",
    RENTAL_PLAN: "rental-plan",
    RENTAL_PLAN_ID: "rental-plan/:id",
    EDIT_ID: "edit/:id",
    EMPTY_ID: ":id",

    // ROUTER_ADMIN
    ADMIN: "/admin",
    LOGIN: "/admin/login",
    SPACE: {
        GROUP_EDIT_ID: "group/edit/:idGroup",
        GROUP_EDIT: "group/edit",
        DETAIL_ADD_TRACKING_LINK: "tracking-links/add/rental_space",
        DETAIL_ADD_TRACKING_LINK_ID: "tracking-links/add/rental_space/:id",
        ADD_TRACKING_LINK: "tracking-links/draft-add/rental_space",
        ADD_TRACKING_LINK_ID: "tracking-links/draft-add/rental_space/:id",
        TRACKING_LINK: "booking-system/draft-advanced-settings",
        TRACKING_LINK_ID: "booking-system/draft-advanced-settings/:id",
        FLOOR_PLAN: "floor-plan",
        FLOOR_PLAN_ID: "floor-plan/:id",
        DIRECTIONS_STATION_IMAGES: "directions-station-images",
        DIRECTIONS_STATION_IMAGES_ID: "directions-station-images/:id",
        FACADE_IMAGES: "facade-images",
        FACADE_IMAGES_ID: "facade-images/:id",
        PANORAMA_IMAGES: "panorama-images",
        PANORAMA_IMAGES_ID: "panorama-images/:id",
        PLAN_EDIT: "plan/edit",
        PLAN_EDIT_ID: "plan/edit/:id",
        GROUP_MANAGE_ID: "group/manage/:id",
        PAGE_MANAGE_ID: "page/manage/:id",
        PAGE_MANAGE: "page/manage",
        MESSAGE_MANAGE_ID: "message/manage/:id",
        MESSAGE_MANAGE: "message/manage",
        GROUP_MANAGE: "group/manage",
        GROUP_ADD_ID: "group/add/:id",
        GROUP_ADD: "group/add",
        GENERAL: "general",
        IMAGES_ID: "images/:id",
        IMAGES: "images",
        EQUIPMENT_INFORMATION: "equipment-information",
        EQUIPMENT_INFORMATION_ID: "equipment-information/:id",
        BOOKING_SYSTEM: "booking-system",
        RESERVATION_SYSTEM: "reservation-system",
        RESERVATION_SYSTEM_ID: "reservation-system/:id",
        TRANSPORTATION_FACILITIES: "transportation_facilities",
        TRANSPORTATION_FACILITIES_ID: "transportation_facilities/:id",
        RESERVATION_OPTIONS: "reservation-options",
        RENTAL_INTERVAL_CONFIG_OVERRIDE: "rental-interval-config-override",
        RENTAL_INTERVAL_CONFIG_OVERRIDE_ID: "rental-interval-config-override/:id",
        BOOKING_SYSTEM_ADVANCED_SETTINGS: "booking-system-advanced-settings",
        BOOKING_SYSTEM_ADVANCED_SETTINGS_ID: "booking-system-advanced-settings/:id",
        RESERVATION_SYSTEM_RESERVATION_OPTIONS: "reservation-system-reservation-options",
        RESERVATION_SYSTEM_RESERVATION_OPTIONS_ID: "reservation-system-reservation-options/:id",
        RENTAL_PLAN: "rental-plan",
        RENTAL_PLAN_EDIT_ROUTER: {
            RENTAL_PLAN_ADD: "add-plan",
            RENTAL_PLAN_ADD_ID: "add-plan/:id",
        },
        LIST_PLAN_INTERVAL: "list-plan-interval",
        ADD_PLAN_INTERVAL: "plan-interval",
        EDIT_PLAN_INTERVAL: "edit-plan-interval",
        EMAIL_MESSAGE: "page-and-email-message",
        APPROVAL: "approval",
        RENTAL_PLAN_DETAIL_MESSAGE: "rental-plan-detail-message",
        RENTAL_PLAN_DETAIL_PAGE: "rental-plan-detail-page",
        RENTAL_PLAN_DETAIL_MESSAGE_ID: "rental-plan-detail-message/:id",
        RENTAL_PLAN_DETAIL_PAGE_ID: "rental-plan-detail-page/:id",
    },
    USER_MANAGER: "user-manage",
    ORDER: "rental-spaces",
    TOUR: "tour",
    INQUIRIES: "inquiries",
    INQUIRIES_DETAIL: "inquiries/view/:id",
    TOUR_MANAGER: {
        TOUR_LIST: "list",
        TOUR_SETTING: "setting",
        TOUR_GUIDE: "guide",
        TOUR_DETAIL: "tour/:id",
    },
    DASHBOARD: "dashboard",
    CONFIGURATION: "configuration",
    RESERVATIONS: "reservations",
    LIST_CUSTOMER: "list-customer",
    RESERVATION_CALENDAR: "reservation-calendar",
    RESERVATION_REGISTER: "reservation-register",
    CUSTOMER_VIEW_ID: "customer-view/:id",
    CUSTOMER_VIEW: "customer-view",
    SYSTEM_CONFIG: "system-config",
    NEWS: "news",
    CUSTOMER_NEWS: "customer-news",
    FAQ: "faq",
    STATIC_PAGE: "static-page",
    HTML_PAGE: "html-page",
    RENTAL_SPACE_COMPILATION: "rental-space-compilation",
    SLIDE: "slide",
    META: "meta",
    RENTAL_SPACE_USE_PURPOSE: "rental-space-use-purpose",
    RENTAL_SPACE_EQUIPMENT_INFORMATION: "rental-space-equipment-information",
    AREA: "area",
    AREA_GROUP: "area-group",
    EMAIL_TEMPLATE: "email-template",
    RENTAL_SPACE_POINTS: "rental-space-points",
    ORGANIZATION: "organization",
    REQUEST_MANAGEMENT: "request-management",
    DOCUMENTATION: "documentation/explorer/browse",
    FOOTER_LINKS: "footer_links",
    HOLIDAY_INFO: "holiday-info",
    PAYOUT: "payout",
    RENTAL_SPACE_COUPONS: "rental-space-coupons",
    CAMPAIGN: "campaign",
    TRACKING_LINKS: "tracking-links",
    XML_EXPORT: "xml-export",
    CSV_EXPORT: "csv-export",
    FIRST_CONTRACTOR: "first-contractor",
    EXTERNAL_RESERVATION: "external-reservation",
    STATIC_PAGE_ADD: "static-page-add",
    EMAIL_TEMPLATE_ADD: "email-template/add",
    HOLIDAY_IMPORT:"holiday-info-import",

    // ROUTER_CUSTOMER
    REGISTER_CUSTOMER: "/register",
    LOGIN_CUSTOMER: "/login",
    OVERVIEW_USER: "overview-user",
    SPACE_DETAILS_CLIENT: "space-details-client",
    SPACE_TOUR: "/space/tour",
};

export const MODULE_STORE = {
    AUTH: {
        NAME: "AUTH",
        GETTERS: {},
        ACTIONS: {},
        MUTATIONS: {},
    },

    COMMON: {
        NAME: "COMMON",
        GETTERS: {
            GET_IS_LOADING: "GET_IS_LOADING",
        },
        ACTIONS: {},
        MUTATIONS: {},
    },
};

export const TYPE_SCREEN = {
    SPACE_ADDING: "space_adding",
    SPACE_EDITING: "space_editing",
};

export const TYPE_USER = {
    USER: "user",
    ADMIN: "admin",
};
